map2 = [
    "",
    "",
    "",
    "",
    "",
    "              A",
    " ",
    "       A",
    "",
    "",
    "        DDDDDDD                                                                                  ",
    "",
    "S  P           UUUU                       C                                                   F  ",
    "GGGGGGGGSSSSSSSGGGGGGGGGGGGGaGGGGGGGGGGGGGGGGGGGGG   GGGGGGGGGGG   GGGGGGGGGGGGDDDDGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG   GGGGGGGGGGG   GGGGGGGGGGGGDDDDGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG   DDDDDDDDDDD   GGGGGGGGGfffDDDDGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG   DDDDDDDDDDD   GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG   DDDDDDDDDDD   GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "                                                     GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG       "
]

barrier2 = [0, 30, 200,3]
vertices2 = [0, 2910, 0 , 540]
